version: '3.4'

services:
  mongodb:
    image: mongo:4.4.1-bionic
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

  redis:
    image: redis:6.0.8-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  data:
  redis: {}
